routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This application Design and develop by Md Khalid Hossain
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('config/cache',function(){
    $exitCode = Artisan::call('config:cache');
}); 

Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    // return what you want
});

Route::get('logout',function(){
    return view('errors.404');
});

Route::get('/', 'MainController@index');
Route::get('/about_us/vission_&_mission', 'MainController@vission');
Route::get('/about_us/our_principles', 'MainController@principles');
Route::get('/about_us/founder_members', 'MainController@founders');
Route::get('/about_us/executive_members', 'MainController@executive');
Route::get('/about_us/general_members', 'MainController@general');
Route::get('/contact_us', 'MainController@contact');
Route::get('/about_us/member_register', 'MainController@register');
Route::post('/member_register', 'MainController@saveregister');

Route::get('/shop', 'MainController@shop');
Route::get('/blog', 'MainController@blog');

Route::get('/services/Transport_fleet_management', 'MainController@fleet_management');
Route::get('/services/Shondhi_Bazar', 'MainController@Shondhi_Bazar');
Route::get('/services/Organic_Food', 'MainController@Organic_Food');

Route::get('/image_gallery', 'MainController@imagegallery');
Route::get('/video_gallery', 'MainController@videogallery');

Route::get('kadmin/members/inactive', 'Admin\\MemberController@inactive');
Route::get('kadmin/members/ec-member', 'Admin\\MemberController@ecmember');

Route::group(['prefix'=>'kadmin'], function(){
    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
    Route::get('/userList', 'UserController@Index')->name('userlist');
    Route::post('/createUser', 'UserController@storeuser')->name('storeuser');
    Route::get('/changePassword', 'UserController@EditUser')->name('EditUser');
    Route::patch('/changePassword', 'UserController@Update');
    Route::delete('/userdelete/{id}', 'UserController@Destory');
    Route::get('/applications/approvedlist', 'Admin\\RegisterController@approvedlist');
    Route::get('/applications/rejectedlist', 'Admin\\RegisterController@rejectedlist');
    Route::get('/applications/pdfdownload/{id}', 'Admin\\RegisterController@pdfdownload');

    Route::get('/payment/print/{id}', 'Admin\\PrintController@prnpriview');

    Route::resource('/poems', 'Admin\\PoemsController');
    Route::resource('/members', 'Admin\\MemberController');
    Route::resource('/applications', 'Admin\\RegisterController');
    Route::resource('/paymenttypes', 'Admin\\PaymentTypeController');
    Route::resource('/payment', 'Admin\\PaymentController');
    Route::resource('/meeting-minutes', 'Admin\\MeetingController');
});

Route::resource('kadmin/photo-gallery', 'Admin\\PhotoGalleryController');
Route::resource('kadmin/gallery-images', 'Admin\\GalleryImageController');
Route::resource('kadmin/video-gallery', 'Admin\\VideoGalleryController');

Route::get('/{any}', function ($any) {
  return Redirect::to('/');
})->where('any', '.*');

app/Payment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'payments';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['amount', 'date', 'status', 'content', 'user_id', 'payment_type_id', 'member_id'];

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function paymentType()
    {
        return $this->belongsTo('App\PaymentType', 'payment_type_id');
    }

    public function member()
    {
        return $this->belongsTo('App\Member', 'member_id');
    }


}

app/PaymentType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PaymentType extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'payment_types';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'date', 'status', 'content'];

    public function payment()
    {
        return $this->hasMany('App\Payment');
    }

}

app/Http/Controllers/Admin/PaymentController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Payment;
use App\Member;
use App\PaymentType;
use App\User;

use Session;
use Auth;

class PaymentController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Payment::all();
        return view('admin.payment.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $type = PaymentType::where('status', '=', 1)->get();
        $users = User::where('status', '=', 1)->get();
        $members = Member::where('status', '=', 1)->get();
        return view('admin.payment.create', compact('type', 'users', 'members'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $requestData = $request->all();
        Payment::create($requestData);

        return redirect('kadmin/payment')->with('flash_message', 'Payment added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/payment/create.blade.php
@extends('layouts.dashlayout')

@section('content')
  
   <div class="container-fluid">
       <h3 class="page-title">Resive new Payment</h3>
       <div class="row">
           <div class="col-md-12">
               <div class="panel">
                   <div class="panel-heading">
                       @if ($errors->any())
                           <ul class="alert alert-danger">
                               @foreach ($errors->all() as $error)
                                   <li>{{ $error }}</li>
                               @endforeach
                           </ul>
                       @endif
                   </div>
                   <div class="panel-body">
                       <form method="POST" action="{{ route('payment.store') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                           {{ csrf_field() }}
                       <div class="row">
                           <div class="col-md-6">
                              <input type="text" name="user_id" style="display: none;" value="{{ Auth::user()->id }}">
                              <div class="form-group">
                                   <label for="name">Payment Type</label>
                                   <select class="form-control" name="payment_type_id" required="required">
                                       <option value="">Select an Option</option>
                                       @foreach($type as $types)
                                       <option value="{{ $types->id }}">{{ $types->title }}</option>
                                       @endforeach
                                   </select>
                               </div>
                               <div class="form-group">
                                   <label for="name">Payment For</label>
                                   <select class="form-control" name="member_id" required="required">
                                       <option value="">Select an Option</option>
                                       @foreach($members as $member)
                                       <option value="{{ $member->id }}">{{ $member->name }}</option>
                                       @endforeach
                                   </select>
                               </div>
                               <div class="form-group">
                                   <label for="amount">Amount</label>
                                   <input type="text" class="form-control" id="amount" name="amount" placeholder="Amount" required="required">
                               </div>
                               
                               <div class="form-group">
                                   <label for="date">Date</label>
                                   <input type="date" class="form-control" id="date" name="date" placeholder="Date">
                               </div>
                               
                               <div class="form-group">
                                   <label for="name">Details</label>
                                   <textarea class="form-control" rows="5" name="content"></textarea>
                               </div>
                               <div class="form-group">
                                   <button type="submit" class="btn btn-success">Save</button>
                                   <button type="reset" class="btn btn-info">Reset</button>
                               </div>
                               
                           </div>
                           <div class="col-md-6">
                           	
                           </div>
                           
                       </div>
                       </form>
                   </div>
               </div>
           </div>
       </div>
   </div>
    
@endsection

resources/views/admin/payment/index.blade.php
@extends('layouts.dashlayout')

@section('content')
  
    
<div class="container-fluid">
    <h3 class="page-title">Subscription List</h3>
    <a class="btn btn-primary" href="{{ route('payment.create') }}">Add New</a> 
    <hr>
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    @if(Session::has('flash_message'))
					    <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {!! session('flash_message') !!}</em></div>
					@endif
                </div>
                <div class="panel-body">
                    <div class="row">
                    	<table class="table table-bordered table-hover">
                    		<thead>
	                    		<tr>
	                    			<th>Sl No</th>
	                    			<th>Title</th>
	                    			<th>Title</th>
	                    			<th>Amount (BDT)</th>
	                    			<th>Date</th>
	                    			
	                    			<th>Action</th>
	                    		</tr>
                    		</thead>
                    		<tbody>
                    			 @if(count($data)>0)
	                    			@foreach($data as $item)
	                    				<tr>
	                    					<td>{{ $loop->iteration }}</td>
	                    					<td>{{ $item->member->name }}</td>
	                    					<td>{{ $item->paymentType->title }}</td>
	                    					<td>{{ $item->amount }}</td>
	                    					<td>{{ $item->date }}</td>
	                    					<td>
	                    						<a href="{{ url('/kadmin/payment/' . $item->id . '/edit') }}" title="Edit Poem"><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit</button></a>
	                    						<a href="{{ url('/kadmin/payment/print/' . $item->id) }}" title="Edit Poem"><button class="btn btn-danger btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Print</button></a>
                                                
	                    					</td>
	                    				</tr>
	                    			@endforeach
                    			@else
                    			<p>No data found</p>
                    			@endif 
                    		</tbody>

                    	</table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/payment/print.blade.php
@extends('layouts.printLayout')

@section('content')
  
    
<div class="container-fluid">
    <h3 class="page-title text-center">Invoice</h3>
    <br>
    <p style="float: right;">Date: {{ date("Y/m/d") }}</p>
    <br>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <div class="panel">
                <div class="panel-heading">
                    <table class="table">
                        <tr>
                            <th width="25%">Name</th>
                            <td>{{ $data->member->name }}</td>
                        </tr>
                        <tr>
                            <th width="25%">Mobile</th>
                            <td>{{ $data->member->mobile }}</td>
                        </tr>
                        <tr>
                            <th width="25%">Payment Date</th>
                            <td>{{ $data->date }}</td>
                        </tr>
                    </table>
                </div>
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th width="10%">Sl No.</th>
                                <th width="25%">Payment Type</th>
                                <th width="40%">Details</th>
                                <th width="20%">Amount (BDT)</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1.</td>
                                <td>{{ $data->paymentType->title }}</td>
                                <td>{{ $data->content }}</td>
                                <td>{{ number_format($data->amount, 2) }}</td>
                                <td></td>
                            </tr>
                        </tbody>

                        <tfoot style="border-top: 1px solid #000">
                            <tr>
                                <td colspan="3">Total Amount</td>
                                <td>{{ number_format($data->amount, 2) }} BDT</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection